### **Dự Báo Phụ Tải Điều Độ**

In [ ]:
!pip install tensorflow


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 644.9/644.9 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 73.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 101.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 86.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 106.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 18.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 5.1 MB/s eta 0:00:00


In [ ]:
# @title Tải thư viện
import tensorflow as tf
from tensorflow import keras
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras import backend as K
from sklearn import preprocessing

In [ ]:
# @title Tải dữ liệu
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

file_path = '/content/drive/My Drive/Code-1/Thực tập 1-Dự báo phụ tải/Đề tài/du_lieu_phu_tai.csv'
df = pd.read_csv(file_path)
df.head()

Mounted at /content/drive


,thoiGian,congSuatMB,congSuatMT,congSuatMN,congSuatHT,ngay,Da_Nang_nhietDo,Hanoi_nhietDo,Ho_Chi_Minh_City_nhietDo,Da_Nang_doAm,Hanoi_doAm,Ho_Chi_Minh_City_doAm
0,1/1/2023 0:30,8893.5,2133.8,9313.8,20341.1,1/1/2023,20.4,11.15,23.20,80.0,76.0,66.0
1,1/1/2023 1:00,9321.5,2081.3,9122.3,20525.1,1/1/2023,20.2,10.90,22.90,82.0,77.0,67.0
2,1/1/2023 1:30,8674.0,2088.3,8895.7,19658.0,1/1/2023,19.9,10.80,22.65,84.0,77.5,68.5
3,1/1/2023 2:00,8435.8,2107.1,8839.7,19382.6,1/1/2023,19.6,10.70,22.40,86.0,78.0,70.0
4,1/1/2023 2:30,8302.3,2121.4,8927.6,19351.3,1/1/2023,19.6,10.70,22.15,85.5,77.5,71.5


In [ ]:
# @title Chuẩn hoá dữ liệu
# Construction of the series
df.drop(["thoiGian","congSuatHT","ngay"],axis=1,inplace=True)

# @title Chia tập huấn luyện, kiểm thử và kiểm tra. (0.8, 0.1, 0.1)
percentage = 0.8
splitting_time = int(len(df) * percentage)
splitting_time2 = int(len(df)*0.1)

train_x = np.array(df.values[:splitting_time],dtype=np.float32)
val_x = np.array(df.values[splitting_time:splitting_time + splitting_time2],dtype=np.float32)
test_x = np.array(df.values[splitting_time + splitting_time2:],dtype=np.float32)

print("train dataset size : %d" %len(train_x))
print("validation dataset size : %d" %len(val_x))
print("test dataset size : %d" %len(test_x))

train_x = tf.convert_to_tensor(train_x)
val_x = tf.convert_to_tensor(val_x)
test_x = tf.convert_to_tensor(test_x)

scaler = preprocessing.MinMaxScaler()
scaler.fit(train_x)

# Lưu scaler vào file
import os
import joblib

# Kiểm tra sự tồn tại của file scaler.pkl
if not os.path.exists('/content/drive/My Drive/Code-1/Thực tập 1-Dự báo phụ tải/Đề tài/scaler.pkl'):
    # Nếu file chưa tồn tại, lưu scaler vào file
    joblib.dump(scaler, '/content/drive/My Drive/Code-1/Thực tập 1-Dự báo phụ tải/Đề tài/scaler.pkl')
    print("Đã lưu scaler vào file 'scaler.pkl'.")
else:
    # Nếu file đã tồn tại, không lưu lại
    print("File 'scaler.pkl' đã tồn tại, không cần lưu lại.")

train dataset size : 31851
validation dataset size : 3981
test dataset size : 3982
File 'scaler.pkl' đã tồn tại, không cần lưu lại.


In [ ]:
# @title Chuẩn hoá dữ liệu 2
import joblib

# Tải scaler từ file
scaler = joblib.load('/content/drive/My Drive/Code-1/Thực tập 1-Dự báo phụ tải/Đề tài/scaler.pkl')

# Sử dụng scaler để chuẩn hóa dữ liệu
train_x_norm = scaler.transform(train_x)
val_x_norm = scaler.transform(val_x)
test_x_norm = scaler.transform(test_x)

print("train_x_norm: ",train_x_norm.shape)
print(train_x_norm);print()

print("val_x_norm: ",val_x_norm.shape)
print(val_x_norm);print()

print("test_x_norm: ",test_x_norm.shape)
print(test_x_norm);print()

train_x_norm:  (31851, 9)
[[0.16571517 0.21048736 0.22657023 ... 0.70588235 0.69620253 0.55844156]
 [0.18630031 0.19969156 0.21548145 ... 0.73529412 0.70886076 0.57142857]
 [0.15515807 0.201131   0.20236022 ... 0.76470588 0.71518987 0.59090909]
 ...
 [0.47489627 0.43855641 0.66419802 ... 0.43382353 0.2278481  0.51298701]
 [0.48987821 0.43756941 0.72632996 ... 0.42647059 0.2278481  0.48051948]
 [0.52792703 0.4685585  0.77077773 ... 0.41176471 0.2278481  0.46753247]]

val_x_norm:  (3981, 9)
[[0.55969931 0.49790251 0.75633623 ... 0.39705882 0.2278481  0.45454545]
 [0.58309328 0.5372198  0.76499301 ... 0.41176471 0.22151899 0.45454545]
 [0.59404472 0.56092945 0.77025659 ... 0.42647059 0.21518987 0.45454545]
 ...
 [0.5649462  0.59191422 0.60880193 ... 0.66176471 0.24050633 0.54545455]
 [0.52513266 0.54005139 0.60012982 ... 0.63235294 0.2278481  0.51948052]
 [0.47428624 0.54200737 0.57263015 ... 0.60294118 0.21518987 0.49350649]]

test_x_norm:  (3982, 9)
[[0.44626893 0.51555353 0.59579204 ..

In [ ]:
# @title Giá trị thử
Thời tiết
[
    [20.4, 11.15, 23.2, 80, 76, 66],
    [20.2, 10.9, 22.9, 82, 77, 67],
    [19.9, 10.8, 22.65, 84, 77.5, 68.5],
    [19.6, 10.7, 22.4, 86, 78, 70],
    [19.6, 10.7, 22.15, 85.5, 77.5, 71.5],
    [19.6, 10.7, 21.9, 85, 77, 73],
    [19.6, 10.6, 21.85, 84.5, 77, 72.5],
    [19.6, 10.5, 21.8, 84, 77, 72],
    [19.5, 10.5, 22.05, 85, 77, 70.5],
    [19.4, 10.5, 22.3, 86, 77, 69],
    [19.4, 10.4, 22.25, 87.5, 77.5, 70],
    [19.4, 10.3, 22.2, 89, 78, 71],
    [19.55, 10.6, 22.55, 85, 79.5, 75.5],
    [19.7, 10.9, 22.9, 81, 81, 80],
    [19.9, 12.2, 23.05, 81, 76, 79],
    [20.1, 13.5, 23.2, 81, 71, 78],
    [20.1, 14.5, 23.7, 81.5, 65, 76.5],
    [20.1, 15.5, 24.2, 82, 59, 75],
    [20.25, 16.15, 25, 81.5, 56.5, 71.5],
    [20.4, 16.8, 25.8, 81, 54, 68],
    [20.9, 17.5, 26.4, 79, 52.5, 65.5],
    [21.4, 18.2, 27, 77, 51, 63],
    [21.3, 18.8, 27.5, 77, 49, 60],
    [21.2, 19.4, 28, 77, 47, 57],
    [21.1, 19.7, 28.35, 78, 46.5, 56],
    [21.0, 20.0, 28.7, 79, 46, 55],
    [21.0, 20.2, 28.5, 79, 46, 56],
    [21.0, 20.4, 28.3, 79, 46, 57],
    [20.95, 20.45, 28.45, 80, 46, 57],
    [20.9, 20.5, 28.6, 81, 46, 57],
    [20.9, 20.35, 28.85, 80.5, 46.5, 57],
    [20.9, 20.2, 29.1, 80, 47, 57]
]


Mục tiêu (Công suất lưới)
[
    [8893.5, 2133.8, 9313.8],
    [9321.5, 2081.3, 9122.3],
    [8674.0, 2088.3, 8895.7],
    [8435.8, 2107.1, 8839.7],
    [8302.3, 2121.4, 8927.6],
    [8374.3, 2142.6, 8847.2],
    [8372.2, 2015.1, 8819.4],
    [8387.6, 2016.3, 8789.0],
    [8740.0, 2132.8, 8738.7],
    [8805.2, 2241.8, 8819.6],
    [9090.6, 2335.7, 8618.3],
    [9325.6, 2410.3, 8220.3],
    [10154.3, 2293.4, 7950.5],
    [10727.0, 2282.0, 7876.5],
    [10745.0, 2222.8, 8092.9],
    [11101.3, 2224.1, 7715.5],
    [11125.5, 2095.8, 7906.2],
    [11131.3, 2098.7, 7835.9],
    [10692.0, 1846.6, 8025.3],
    [10927.7, 1883.6, 8109.2],
    [11287.7, 1904.2, 8231.2],
    [10960.0, 1848.3, 7857.6],
    [10571.7, 1789.9, 7674.8],
    [9968.0, 1922.2, 7355.4],
    [9708.5, 1803.5, 7881.3],
    [9770.0, 1680.9, 8255.8],
    [9947.9, 1698.2, 9210.4],
    [10208.8, 1763.7, 9193.1],
    [10163.0, 1991.5, 8973.3],
    [10424.2, 2472.0, 9165.7],
    [10779.7, 2335.8, 9291.4],
    [11092.3, 2620.5, 9159.1]
]

In [3]:
# @title Chạy demo (Phiên bản hoàn chỉnh)

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os
import numpy as np
import joblib
import ipywidgets as widgets
from IPython.display import display


from tensorflow import keras
import pandas as pd

from sklearn import preprocessing

import tensorflow as tf
from tensorflow.keras import layers, regularizers
from tensorflow.keras import backend as K


# ================== MODEL DEFINITION ==================

# @title Định nghĩa mô hình (dùng)
import tensorflow as tf
from tensorflow.keras import layers, regularizers
from tensorflow.keras import backend as K

# Định nghĩa mô hình WaveNet cho dự báo đa mục tiêu
# len_seq: độ dài chuỗi đầu vào
def model_wavenet_timeseries(
    len_seq,
    len_out,
    dim_exo,
    dim_target,       # số kênh target (ví dụ 3)
    nb_filters,
    dim_filters,
    dilation_depth,
    use_bias,
    res_l2,
    final_l2,
    batch_size

):
    # Input exogenous series
    input_exo = tf.keras.Input(shape=(len_seq, dim_exo), name='input_exo')
    # Input multi-target series
    input_target = tf.keras.Input(shape=(len_seq, dim_target), name='input_target')

    outputs = []
    # Khởi tạo 2 biến sẽ cập nhật cho từng bước dự báo
    exo_inp = input_exo
    tgt_inp = input_target

    for t in range(len_out):
        # --- Causal Convolution cho exogenous ---
        pad_exo = layers.Lambda(
            lambda x: K.temporal_padding(x, padding=((dim_filters - 1), 0)),
            output_shape=lambda s: (s[0], s[1] + dim_filters - 1, s[2])
        )(exo_inp)
        conv_exo = layers.Conv1D(
            filters=nb_filters,
            kernel_size=dim_filters,
            dilation_rate=1,
            use_bias=use_bias,
            activation=None,
            kernel_regularizer=regularizers.l2(res_l2),
            name=f'causal_conv_exo_{t}'
        )(pad_exo)

        # --- Causal Convolution cho target ---
        pad_tgt = layers.Lambda(
            lambda x: K.temporal_padding(x, padding=((dim_filters - 1), 0)),
            output_shape=lambda s: (s[0], s[1] + dim_filters - 1, s[2])
        )(tgt_inp)
        conv_tgt = layers.Conv1D(
            filters=nb_filters,
            kernel_size=dim_filters,
            dilation_rate=1,
            use_bias=use_bias,
            activation=None,
            kernel_regularizer=regularizers.l2(res_l2),
            name=f'causal_conv_tgt_{t}'
        )(pad_tgt)

        skip_connections = []

        # --- Lớp dilated đầu tiên cho exogenous & target ---
        def dilated_block(x, filters_out, name_prefix):
            pad_amt = 2 * (dim_filters - 1)
            z = layers.Lambda(
                lambda y: K.temporal_padding(y, padding=(pad_amt, 0)),
                output_shape=lambda s: (s[0], s[1] + pad_amt, s[2])
            )(x)
            z = layers.Conv1D(
                filters=nb_filters,
                kernel_size=dim_filters,
                dilation_rate=2,
                activation='relu',
                use_bias=use_bias,
                kernel_regularizer=regularizers.l2(res_l2),
                name=f'{name_prefix}_dilated1'
            )(z)
            skip = layers.Conv1D(
                filters_out,
                kernel_size=1,
                padding='same',
                use_bias=False,
                kernel_regularizer=regularizers.l2(res_l2),
                name=f'{name_prefix}_skip1'
            )(z)
            res = layers.Conv1D(
                filters_out,
                kernel_size=1,
                padding='same',
                use_bias=False,
                kernel_regularizer=regularizers.l2(res_l2),
                name=f'{name_prefix}_res1'
            )(z)
            return skip, res

        skip_exo1, res_exo1 = dilated_block(conv_exo, dim_exo, f'exo_{t}')
        skip_tgt1, res_tgt1 = dilated_block(conv_tgt, dim_target, f'tgt_{t}')
        skip_connections += [layers.Concatenate(axis=-1)([skip_exo1, skip_tgt1])]

        # Cộng residual vào input
        exo_out = layers.Add()([exo_inp, res_exo1])
        tgt_out = layers.Add()([tgt_inp, res_tgt1])

        # Kết hợp exo & target
        out = layers.Concatenate(axis=-1)([exo_out, tgt_out])

        # --- Các lớp dilated tiếp theo ---
        for i in range(2, dilation_depth + 1):
            pad_amt = (2 ** i) * (dim_filters - 1)
            z = layers.Lambda(
                lambda y, p=pad_amt: K.temporal_padding(y, padding=(p, 0)),
                output_shape=lambda s, p=pad_amt: (s[0], s[1] + p, s[2])
            )(out)
            z = layers.Conv1D(
                filters=nb_filters,
                kernel_size=dim_filters,
                dilation_rate=2 ** i,
                activation='relu',
                use_bias=use_bias,
                kernel_regularizer=regularizers.l2(res_l2),
                name=f'dilated_conv_{i}_{t}'
            )(z)
            skip_i = layers.Conv1D(
                dim_exo + dim_target,
                kernel_size=1,
                padding='same',
                use_bias=False,
                kernel_regularizer=regularizers.l2(res_l2),
                name=f'skip_{i}_{t}'
            )(z)
            res_i = layers.Conv1D(
                dim_exo + dim_target,
                kernel_size=1,
                padding='same',
                use_bias=False,
                kernel_regularizer=regularizers.l2(res_l2),
                name=f'res_{i}_{t}'
            )(z)
            out = layers.Add()([out, res_i])
            skip_connections.append(skip_i)

        # Tổng hợp skip connections
        total_skip = layers.Add(name=f'total_skip_{t}')(skip_connections)
        # Output linear
        lin = layers.Activation('linear', name=f'lin_out_{t}')(total_skip)

        # Tạo dự báo multi-target cho bước t
        out_f_tgt = layers.Conv1D(
            dim_target,
            kernel_size=1,
            padding='same',
            kernel_regularizer=regularizers.l2(final_l2),
            name=f'out_f_tgt_{t}'
        )(lin)
        # Lấy step prediction
        step_pred = layers.Lambda(
            lambda y: y[:, -1:, :],
            output_shape=lambda s: (s[0], 1, dim_target)
        )(out_f_tgt)
        outputs.append(step_pred)

        # Cập nhật input window cho bước tiếp theo
        # Exogenous
        new_exo = layers.Concatenate(axis=1)([
            exo_inp,
            layers.Lambda(lambda y: y[:, -1:, :])(layers.Conv1D(dim_exo,1,padding='same')(lin))
        ])
        exo_inp = layers.Lambda(lambda y: y[:, 1:, :])(new_exo)
        # Target
        new_tgt = layers.Concatenate(axis=1)([
            tgt_inp,
            step_pred
        ])
        tgt_inp = layers.Lambda(lambda y: y[:, 1:, :])(new_tgt)

    # Stack outputs thành (batch, len_out, dim_target)
    stacked = layers.Lambda(
        lambda xs: tf.concat(xs, axis=1),
        output_shape=lambda s: (None, len_out, dim_target)
    )(outputs)

    model = tf.keras.Model([input_exo, input_target], stacked)
    return model


# ================== LOAD MODEL & SCALER ==================


def compute_len_seq(dilation_depth):
  return (2 ** dilation_depth * 2)

nb_filters = 96
dim_filters = 2
dilation_depth = 4     # len_seq = 32
use_bias = True
res_l2 = 0
final_l2 = 0

batch_size = 128
len_out = 18
dim_exo = 6
dim_target = 3

len_seq = compute_len_seq(dilation_depth)
print(len_seq)

# ================== THIẾT LẬP TPU/GPU ==================
try:
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver.connect()
    strategy = tf.distribute.TPUStrategy(tpu)
    print("Running on TPU:", tpu.master())
    global_batch_size = batch_size * strategy.num_replicas_in_sync
except ValueError:
    gpus = tf.config.list_physical_devices('GPU')
    if gpus:
        strategy = tf.distribute.MirroredStrategy()
        print(f"Running on {len(gpus)} GPU(s)")
        global_batch_size = batch_size
    else:
        strategy = tf.distribute.get_strategy()
        print("Running on CPU")
        global_batch_size = batch_size

# ================== CÀI ĐẶT ĐƯỜNG DẪN ==================
checkpoint_path = "/content/drive/My Drive/Code-1/Thực tập 1-Dự báo phụ tải/Đề tài/checkpoints/best_model.weights.h5"
scaler_path   = '/content/drive/My Drive/Code-1/Thực tập 1-Dự báo phụ tải/Đề tài/scaler.pkl'


# ================== TẢI MÔ HÌNH ==================
# Sử dụng strategy scope nếu model được lưu với strategy

try:
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver.connect()
    strategy = tf.distribute.TPUStrategy(tpu)
except ValueError:
    strategy = tf.distribute.get_strategy()
with strategy.scope():
        # Ensure the model architecture is the same as the saved model
        model = model_wavenet_timeseries(len_seq, len_out, dim_exo, dim_target, nb_filters, dim_filters, dilation_depth, use_bias, res_l2, final_l2, batch_size)
        # Load the weights
        model.load_weights(checkpoint_path)

scaler = joblib.load(scaler_path)

# ================== WIDGETS ==================
exo_input = widgets.Textarea(
    placeholder='Nhập {} giá trị Exo, dạng: [..]'.format(len_seq),
    description='Exo:', layout={'width':'500px','height':'80px'}
)
target_input = widgets.Textarea(
    placeholder='Nhập {} giá trị Target, dạng: [..]'.format(len_seq),
    description='Tgt:', layout={'width':'500px','height':'80px'}
)
button = widgets.Button(description="Dự báo")
output = widgets.Output()

def on_button_clicked(b):
    with output:
        output.clear_output()
        try:
            # Đọc dữ liệu
            exo = np.array(eval(exo_input.value), dtype=np.float32).reshape(len_seq, dim_exo)
            tgt = np.array(eval(target_input.value), dtype=np.float32).reshape(len_seq, dim_target)

            # Chuẩn hóa theo thứ tự [target, exo]
            comb = np.hstack([tgt, exo])  # Thay đổi thứ tự
            norm = scaler.transform(comb)

            # Tách thành target và exo đã chuẩn hóa
            tgt_n = norm[:, :dim_target][None, ...]  # (1, len_seq, dim_target)
            exo_n = norm[:, dim_target:][None, ...]  # (1, len_seq, dim_exo)


            def create_test_dataset(x_test1, x_test2):
                """Tạo dataset cho dự báo không cần nhãn"""
                dataset = tf.data.Dataset.from_tensor_slices({
                    "input_exo": x_test1,
                    "input_target": x_test2
                })
                return dataset.batch(batch_size=32, drop_remainder=False)  # Điều chỉnh batch_size theo RAM

            input_data = create_test_dataset(exo_n, tgt_n)

            # Dự báo
            pred_n = model.predict(input_data)[0]  # (len_out, dim_target)

            # Inverse scaling
            # Giả định exo không đổi (hoặc xử lý theo nghiệp vụ)
            exo_future = np.repeat(exo[-1], len_out, axis=0)  # (len_out, dim_exo)


            # Tạo buffer [target, exo] cho từng bước dự báo
            inv_predictions = []
            for i, (pred_step, exo_step) in enumerate(zip(pred_n, exo_future)):
                buf = np.zeros((1, dim_target + dim_exo), dtype=np.float32)
                buf[0, :dim_target] = pred_step
                buf[0, dim_target:] = exo_step
                inv = scaler.inverse_transform(buf)[0, :dim_target]
                inv_predictions.append(inv)
                print(f"Bước {i+1}: {inv}")

        except Exception as e:
            print("Lỗi:", e)

button.on_click(on_button_clicked)
display(exo_input, target_input, button, output)


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
32
Running on 1 GPU(s)


Textarea(value='', description='Exo:', layout=Layout(height='80px', width='500px'), placeholder='Nhập 32 giá t…

Textarea(value='', description='Tgt:', layout=Layout(height='80px', width='500px'), placeholder='Nhập 32 giá t…

Button(description='Dự báo', style=ButtonStyle())

Output()